services:
  redis:
    image: docker.io/library/redis:latest
    container_name: rag-redis
    ports:
      - "6379:6379"

  qdrant:
    image: docker.io/qdrant/qdrant:latest
    container_name: rag-qdrant
    ports:
      - "6333:6333"
